version: '3.7'

services:
  students_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students
    ports:
      - "5432:5432"
  student-service:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - students_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/students_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
