version: '3.7'

services:
  books_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
  book-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - books_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/books_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
