version: '3.7'

services:
  loans_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loans
    ports:
      - "5432:5432"
  loan-service:
    build: .
    ports:
      - "8070:8070"
    depends_on:
      - loans_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/loans_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
