spring:
  application:
    name: student-service 
  cloud:
    netflix:
      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        instance:
          hostname: localhost
          prefer-ip-address: true